# Generated by Django 5.1.3 on 2024-11-26 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0002_absensi_delete_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absensi',
            options={},
        ),
        migrations.AlterField(
            model_name='absensi',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='absensi',
            table='absensi',
        ),
    ]
