# Generated by Django 5.1.4 on 2024-12-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0002_alter_pembayaran_status_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='kode_unik',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PembayaranHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('tanggal_approve_tolak', models.DateTimeField(blank=True, null=True)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('status', models.CharField(choices=[('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Ditolak', max_length=50)),
                ('kode_pembayaran', models.CharField(max_length=20)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passionpath_app.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passionpath_app.students')),
            ],
        ),
    ]
