# Generated by Django 5.1.3 on 2024-11-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0003_alter_absensi_options_alter_absensi_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='absensi',
            table=None,
        ),
    ]
