# Generated by Django 5.1.4 on 2024-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0003_pembayaran_kode_unik_pembayaranhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='nomor_rekening_pengirim',
            new_name='nomor_rekening_dan_nama',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='kode_unik',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='tanggal_approve_tolak',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='kode_pembayaran',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='PembayaranHistory',
        ),
    ]
