# Generated by Django 5.1.3 on 2024-12-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0004_alter_absensi_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('nomor_hp_orang_tua', models.CharField(max_length=15)),
                ('tanggal_lahir', models.DateField()),
                ('nama_sekolah', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
