# Generated by Django 5.1.3 on 2024-12-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0006_students_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_ortu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
