# Generated by Django 5.1.3 on 2024-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name_ortu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
