# Generated by Django 5.1.4 on 2024-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0009_students_name_ortu'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id_siswa',
            field=models.CharField(default='S00000', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
