# Generated by Django 5.1.4 on 2024-12-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0012_profile_admin_foto_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_admin',
            name='foto_profil',
        ),
    ]
