# Generated by Django 5.1.4 on 2024-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0013_remove_profile_admin_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_admin',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
