# Generated by Django 5.1.4 on 2024-12-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0014_profile_admin_foto_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_admin',
            old_name='user',
            new_name='username',
        ),
    ]
