# Generated by Django 5.1.4 on 2024-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0016_profileadmin_delete_profile_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('total_modul', models.IntegerField(default=0)),
            ],
        ),
    ]
