# Generated by Django 5.1.4 on 2024-12-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0017_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul_episode', models.CharField(max_length=100)),
                ('deskripsi_episode', models.TextField(blank=True, null=True)),
                ('upload_video', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('link_video', models.URLField(blank=True, null=True)),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='passionpath_app.kelas')),
            ],
        ),
    ]
