# Generated by Django 5.1.4 on 2024-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionpath_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='nomor_rekening_pengirim',
            new_name='nomor_rekening_dan_nama',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='tanggal_approve_tolak',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='kode_pembayaran',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('ditolak', 'Ditolak')], default='pending', max_length=10),
        ),
    ]
